/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControleInfoSerie;
import javax.swing.JButton;
import javax.swing.JLabel;
import model.Serie;

/**
 *
 * @author ncatjpeg
 */
public class InfoSerie extends javax.swing.JFrame {
    private ControleInfoSerie c;
    
    /**
     * Creates new form Video
     * @param serie
     */
    public InfoSerie(Serie serie) {
        initComponents();
        lbl_titulo.setText((serie.getTitulo()));
        lbl_ano.setText((serie.getAno()));
        lbl_diretor.setText((serie.getDiretor()));
        lbl_genero.setText((serie.getGenero()));
        lbl_episodios.setText((serie.getEpisodios()));
        lbl_temporadas.setText((serie.getTemporadas()));
        lbl_situacao.setText((serie.exibirSituacao(serie.getSituacao())));
        c = new ControleInfoSerie(this);
    }

    public JButton getjButton1() {
        return btn_playlist;
    }

    public void setjButton1(JButton jButton1) {
        this.btn_playlist = jButton1;
    }

    public JLabel getLbl_ano() {
        return lbl_ano;
    }

    public void setLbl_ano(JLabel lbl_ano) {
        this.lbl_ano = lbl_ano;
    }

    public JLabel getLbl_diretor() {
        return lbl_diretor;
    }

    public void setLbl_diretor(JLabel lbl_diretor) {
        this.lbl_diretor = lbl_diretor;
    }

    public JLabel getLbl_genero() {
        return lbl_genero;
    }

    public void setLbl_genero(JLabel lbl_genero) {
        this.lbl_genero = lbl_genero;
    }

    public JLabel getLbl_info1() {
        return lbl_episodios;
    }

    public void setLbl_info1(JLabel lbl_info1) {
        this.lbl_episodios = lbl_info1;
    }

    public JLabel getLbl_nome() {
        return lbl_titulo;
    }

    public void setLbl_nome(JLabel lbl_nome) {
        this.lbl_titulo = lbl_nome;
    }

    public JLabel getLbl_episodios() {
        return lbl_episodios;
    }

    public void setLbl_episodios(JLabel lbl_episodios) {
        this.lbl_episodios = lbl_episodios;
    }

    public JLabel getLbl_situacao() {
        return lbl_situacao;
    }

    public void setLbl_situacao(JLabel lbl_situacao) {
        this.lbl_situacao = lbl_situacao;
    }

    public JLabel getLbl_temporadas() {
        return lbl_temporadas;
    }

    public void setLbl_temporadas(JLabel lbl_temporadas) {
        this.lbl_temporadas = lbl_temporadas;
    }

    public JLabel getLbl_titulo() {
        return lbl_titulo;
    }

    public void setLbl_titulo(JLabel lbl_titulo) {
        this.lbl_titulo = lbl_titulo;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titulo = new javax.swing.JLabel();
        lbl_ano = new javax.swing.JLabel();
        lbl_diretor = new javax.swing.JLabel();
        lbl_genero = new javax.swing.JLabel();
        lbl_episodios = new javax.swing.JLabel();
        btn_playlist = new javax.swing.JButton();
        lbl_temporadas = new javax.swing.JLabel();
        lbl_situacao = new javax.swing.JLabel();
        btn_fechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Video");

        lbl_titulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_titulo.setText("Titulo: ");

        lbl_ano.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_ano.setText("Ano: ");

        lbl_diretor.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_diretor.setText("Diretor: ");

        lbl_genero.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_genero.setText("Gênero: ");

        lbl_episodios.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_episodios.setText("Episodios:");

        btn_playlist.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        btn_playlist.setText("Playlist");

        lbl_temporadas.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_temporadas.setText("Temporadas:");

        lbl_situacao.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_situacao.setText("Situação:");

        btn_fechar.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        btn_fechar.setText("Fechar");
        btn_fechar.addActionListener(this::btn_fecharActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_genero, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                            .addComponent(lbl_diretor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_ano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_episodios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_temporadas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_situacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_playlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_fechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lbl_titulo)
                .addGap(18, 18, 18)
                .addComponent(lbl_ano)
                .addGap(18, 18, 18)
                .addComponent(lbl_diretor)
                .addGap(18, 18, 18)
                .addComponent(lbl_genero)
                .addGap(18, 18, 18)
                .addComponent(lbl_episodios)
                .addGap(18, 18, 18)
                .addComponent(lbl_temporadas)
                .addGap(18, 18, 18)
                .addComponent(lbl_situacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btn_playlist)
                .addGap(18, 18, 18)
                .addComponent(btn_fechar)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fecharActionPerformed
        // TODO add your handling code here:
        c.fechar();
    }//GEN-LAST:event_btn_fecharActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Video().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_fechar;
    private javax.swing.JButton btn_playlist;
    private javax.swing.JLabel lbl_ano;
    private javax.swing.JLabel lbl_diretor;
    private javax.swing.JLabel lbl_episodios;
    private javax.swing.JLabel lbl_genero;
    private javax.swing.JLabel lbl_situacao;
    private javax.swing.JLabel lbl_temporadas;
    private javax.swing.JLabel lbl_titulo;
    // End of variables declaration//GEN-END:variables
}
