/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ncatjpeg
 */
public class Video extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Video.class.getName());

    /**
     * Creates new form Video
     */
    public Video() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nome = new javax.swing.JLabel();
        lbl_ano = new javax.swing.JLabel();
        lbl_diretor = new javax.swing.JLabel();
        lbl_genero = new javax.swing.JLabel();
        lbl_descricao = new javax.swing.JLabel();
        lbl_info1 = new javax.swing.JLabel();
        lbl_2 = new javax.swing.JLabel();
        lbl_info3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Video");

        lbl_nome.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_nome.setText("Nome: ");

        lbl_ano.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_ano.setText("Ano: ");

        lbl_diretor.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_diretor.setText("Diretor: ");

        lbl_genero.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_genero.setText("Gênero: ");

        lbl_descricao.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_descricao.setText("Descrição:");
        lbl_descricao.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbl_info1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_info1.setText("Info 1:");

        lbl_2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_2.setText("Info 2:");

        lbl_info3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_info3.setText("Info 3:");

        jButton1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jButton1.setText("Playlist");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_genero, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                            .addComponent(lbl_diretor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_ano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                                    .addComponent(lbl_info1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_info3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(133, 133, 133))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lbl_nome)
                .addGap(18, 18, 18)
                .addComponent(lbl_ano)
                .addGap(18, 18, 18)
                .addComponent(lbl_diretor)
                .addGap(18, 18, 18)
                .addComponent(lbl_genero)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lbl_info1)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_2)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_info3)
                        .addGap(113, 113, 113)
                        .addComponent(jButton1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Video().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JLabel lbl_ano;
    private javax.swing.JLabel lbl_descricao;
    private javax.swing.JLabel lbl_diretor;
    private javax.swing.JLabel lbl_genero;
    private javax.swing.JLabel lbl_info1;
    private javax.swing.JLabel lbl_info3;
    private javax.swing.JLabel lbl_nome;
    // End of variables declaration//GEN-END:variables
}
